const dateString = '2017-10-18 09:00am';
const date = new Date(dateString);

export const ordersResponse = [
  {
    buyer_name: 'John Doe',
    buyer_email: 'john@doe.com',
    source: 'stripe',
    date_purchased: dateString,
    status: 'paid',
    reference: 'aabbccdd',
    transaction_status: 'completed',
    transaction_number: '111222333',
    amount: '70.0',
    discounted_amount: '0.0',
    total_fees: '0.65',
    currency: 'GBP',
    manual_payment_type: 'stripe',
    paypal_pay_key: null,
  },
  {
    buyer_name: 'Andrzej Duda',
    buyer_email: 'prezydent@prezydent.gov.pl',
    source: 'stripe',
    date_purchased: dateString,
    status: 'paid',
    reference: 'eeffgghh',
    transaction_status: 'completed',
    transaction_number: '444555666',
    amount: '35.0',
    discounted_amount: '0.0',
    total_fees: '0.65',
    currency: 'GBP',
    manual_payment_type: 'stripe',
    paypal_pay_key: null,
  },
  {
    buyer_name: 'Jakub Kowalczyk',
    buyer_email: 'j@kowalcz.yk',
    source: 'stripe',
    date_purchased: dateString,
    status: 'paid',
    reference: 'iijjkkll',
    transaction_status: 'completed',
    transaction_number: '777888999',
    amount: '35.0',
    discounted_amount: '0.0',
    total_fees: '0.65',
    currency: 'GBP',
    manual_payment_type: 'stripe',
    paypal_pay_key: null,
  },
];

export const expectedOrders = [
  {
    buyerName: 'John Doe',
    buyerEmail: 'john@doe.com',
    source: 'stripe',
    datePurchased: date,
    status: 'paid',
    reference: 'aabbccdd',
    transactionStatus: 'completed',
    transactionNumber: '111222333',
    amount: '70.0',
    discountedAmount: '0.0',
    totalFees: '0.65',
    currency: 'GBP',
    manualPaymentType: 'stripe',
    paypalPayKey: null,
  },
  {
    buyerName: 'Andrzej Duda',
    buyerEmail: 'prezydent@prezydent.gov.pl',
    source: 'stripe',
    datePurchased: date,
    status: 'paid',
    reference: 'eeffgghh',
    transactionStatus: 'completed',
    transactionNumber: '444555666',
    amount: '35.0',
    discountedAmount: '0.0',
    totalFees: '0.65',
    currency: 'GBP',
    manualPaymentType: 'stripe',
    paypalPayKey: null,
  },
  {
    buyerName: 'Jakub Kowalczyk',
    buyerEmail: 'j@kowalcz.yk',
    source: 'stripe',
    datePurchased: date,
    status: 'paid',
    reference: 'iijjkkll',
    transactionStatus: 'completed',
    transactionNumber: '777888999',
    amount: '35.0',
    discountedAmount: '0.0',
    totalFees: '0.65',
    currency: 'GBP',
    manualPaymentType: 'stripe',
    paypalPayKey: null,
  },
];

export const ticketsResponse = [
  {
    identifier: '111222333111222333',
    order_id: 'aabbccdd',
    first_name: 'John',
    last_name: 'Doe',
    email: 'john@doe.com',
    checked_in: false,
    void: false,
    ticket_type: 'Early Bird + Ball',
    ticket_typeId: '0',
  },
  {
    identifier: '222333444222333444',
    order_id: 'aabbccdd',
    first_name: 'Jane',
    last_name: 'Doe',
    email: 'jane@doe.com',
    checked_in: false,
    void: false,
    ticket_type: 'Early Bird + Ball',
    ticket_type_id: '0',
  },
  {
    identifier: '333444555333444555',
    order_id: 'eeffgghh',
    first_name: 'Andrzej',
    last_name: 'Duda',
    email: 'prezydent@prezydent.gov.pl',
    checked_in: false,
    void: false,
    ticket_type: 'Early Bird + Ball',
    ticket_typeId: '0',
  },
  {
    identifier: '444555666444555666',
    order_id: 'iijjkkll',
    first_name: 'Jakub',
    last_name: 'Kowalczyk',
    email: 'j@kowalcz.yk',
    checked_in: false,
    void: false,
    ticket_type: 'Early Bird + Ball',
    ticket_type_id: '0',
  },
];

export const expectedTickets = [
  {
    identifier: '111222333111222333',
    orderId: 'aabbccdd',
    firstName: 'John',
    lastName: 'Doe',
    email: 'john@doe.com',
    checkedIn: false,
    void: false,
    ticketType: 'Early Bird + Ball',
    ticketTypeId: '0',
  },
  {
    identifier: '222333444222333444',
    orderId: 'aabbccdd',
    firstName: 'Jane',
    lastName: 'Doe',
    email: 'jane@doe.com',
    checkedIn: false,
    void: false,
    ticketType: 'Early Bird + Ball',
    ticketTypeId: '0',
  },
  {
    identifier: '333444555333444555',
    orderId: 'eeffgghh',
    firstName: 'Andrzej',
    lastName: 'Duda',
    email: 'prezydent@prezydent.gov.pl',
    checkedIn: false,
    void: false,
    ticketType: 'Early Bird + Ball',
    ticketTypeId: '0',
  },
  {
    identifier: '444555666444555666',
    orderId: 'iijjkkll',
    firstName: 'Jakub',
    lastName: 'Kowalczyk',
    email: 'j@kowalcz.yk',
    checkedIn: false,
    void: false,
    ticketType: 'Early Bird + Ball',
    ticketTypeId: '0',
  },
];
